### PR TITLE
production server

### PR DESCRIPTION
**Pull request by Ph0tonic**

### CODE REVIEW

**Review by volodymyrss — CHANGES_REQUESTED** [review]
test fails?

**Comment by Ph0tonic** [comment]
> test fails?

Yes, I am working on it, sorry for the delay.

**Review by volodymyrss — APPROVED** [review]

**Comment by Ph0tonic** [comment]
> test fails?

Finally I switch to use cheroot instead of waitress which is faster and seems to not fail with upload of files.

**Comment by volodymyrss** [comment]
why not gunicorn?

**Comment by Ph0tonic** [comment]
Because we were already using cheroot for testing so I just decided to use the same stack.

**Pull request merged**
